job: extension
config:
  name: "my_flux_lora"
  process:
    - type: 'sd_trainer'
      training_folder: "output"
      device: cuda:0
      trigger_word: "mytiggerword"
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: "dataset"
          caption_ext: "txt"
          resolution: [ 1024 ]
      train:
        batch_size: 1
        steps: 1500
        lr: 1e-4
        optimizer: "adamw8bit"
        dtype: bf16
      model:
        name_or_path: "/home/niklaus/flux2-dev-local"
        is_flux: true
